services:
  portafolio:
    container_name: portafolio
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    networks:
      - portafolio-network
    restart: always

networks:
  portafolio-network:
    external: true