services:
  portafolio:
    container_name: portafolio
    image: ghcr.io/Carlos-Javier10/portafolio:latest

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    networks:
      - portafolio-network
    restart: always

networks:
  portafolio-network:
    external: true