version: 2.1

orbs:
  node: circleci/node@5.2

workflows:
  build_and_test:
    jobs:
      - node/install-packages:
          version: '20' # Usa Node.js 20, como en tu configuración actual
          pkg-manager: npm
      - node/run:
          name: Build Application
          version: '20'
          pkg-manager: npm
          command: npm run build