version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build:
    docker:
      - image: cimg/node:20.5 # Imagen oficial de CircleCI con Node.js 20
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Application
          command: npm run build

workflows:
  build_and_test:
    jobs:
      - build
