version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build:
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  test:
    docker:
      - image: circleci/node:20
    parallelism: 4  # Corre el job en 4 contenedores paralelos
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
