version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install
      - run:
          name: Construir la aplicación
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install