apiVersion: v1
kind: ConfigMap
metadata:
  name: portafolio-config
  labels:
    app: portafolio
data:
  # Configuraciones de la aplicación
  API_URL: "https://portafolio.cjdevlabs.com"
  APP_NAME: "Portafolio"
  APP_VERSION: "1.0.0"
