apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: portafolio-pdb
  namespace: portafolio
  labels:
    app: portafolio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: portafolio
