apiVersion: v1
kind: ResourceQuota
metadata:
  name: portafolio-quota
  namespace: portafolio
  labels:
    app: portafolio
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "3"
    limits.memory: 2Gi
    persistentvolumeclaims: "0"
    pods: "10"
    replicationcontrollers: "0"
    secrets: "10"
    services: "5"
    services.loadbalancers: "0"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: portafolio-limits
  namespace: portafolio
  labels:
    app: portafolio
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
