name: Docker Image CI

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR }}

    - name: Build the Docker Compose
      run: docker compose build

    - name: Push the Docker Compose
      run: docker compose push
    - name: Get the Docker Compose
      run: docker compose pull
    - name: Stop the Docker Compose
      run: docker compose down
    - name: Create Docker network if not exists
      run: |
        if (-not (docker network ls --format '{{.Name}}' | Select-String -Pattern '^portafolio-network$')) {
          docker network create portafolio-network
        }
      shell: pwsh
    - name: Start the Docker Compose
      run: docker compose up -d