name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create external network
      run: docker network create portafolio-network || true

    - name: Build the Docker Compose
      run: docker compose build

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker Compose
      run: docker compose push

    - name: Stop the Docker Compose
      run: docker compose down

    - name: Start the Docker Compose
      run: docker compose up -d